export enum Bookmaker {
  BET365 = 'Bet365',
  BETANO = 'Betano',
  BETFAIR = 'Betfair',
  SPORTINGBET = 'Sportingbet',
  PIXBET = 'Pixbet',
  BETSSON = 'Betsson',
  PARIMATCH = 'Parimatch',
  X1BET = '1xBet',
  RIVALRY = 'Rivalry',
  ESTRELASBET = 'EstrelaBet',
  BETNACIONAL = 'Betnacional',
  BET7K = 'Bet7k',
  REIBET = 'Rei do Pitaco',
  MRJACK = 'MrJack.bet',
  BRASILEIRABET = 'BrasileiraBet',
  KTO = 'KTO',
  F12BET = 'F12.bet',
  LUCKSPORTS = 'LuckSports',
}