export enum Sport {
  SOCCER = 'Soccer',
  BASKETBALL = 'Basketball',
  TENNIS = 'Tennis',
  VOLLEYBALL = 'Volleyball',
  HANDBALL = 'Handball',
  BASEBALL = 'Baseball',
  AMERICAN_FOOTBALL = 'American Football',
  RUGBY = 'Rugby',
  HOCKEY = 'Ice Hockey',
  MMA = 'MMA',
  BOXING = 'Boxing',
  FORMULA1 = 'Formula 1',
  MOTORSPORT = 'Motorsport',
  GOLF = 'Golf',
  CYCLING = 'Cycling',
  FUTSAL = 'Futsal',
  TABLE_TENNIS = 'Table Tennis',
  CRICKET = 'Cricket',
  DARTS = 'Darts',
  SNOOKER = 'Snooker',
  BEACH_VOLLEY = 'Beach Volleyball',
  AUSSIE_RULES = 'Aussie Rules',
  WINTER_SPORTS = 'Winter Sports',
  WATER_POLO = 'Water Polo',

  // eSports
  CS2 = 'CS2',
  LOL = 'League of Legends',
  DOTA2 = 'Dota 2',
  VALORANT = 'Valorant',
  RAINBOW6 = 'Rainbow Six',
  CALL_OF_DUTY = 'Call of Duty',
  OVERWATCH = 'Overwatch',
  STARCRAFT2 = 'StarCraft 2',
  FIFA = 'FIFA',
  NBA2K = 'NBA 2K',
  KING_OF_GLORY = 'King of Glory',
  WILD_RIFT = 'Wild Rift',
  ROCKET_LEAGUE = 'Rocket League',
  MOBILE_LEGENDS = 'Mobile Legends',
  ARENA_OF_VALOR = 'Arena of Valor',
}